### ISSUE TITLE
NoSql support

### ISSUE THREAD

**Issue by mvmcjr** [cordialgerm/FluentCache#8]
Hello, would it be possible for fluentcache to create a background worker that would write to a NoSql database and read from it, in case of memory loss (restart/power loss)?

**Comment by evan-rash** [comment]
Hey, FluentCache is intended to make it easy to interact with your cache provider so you don't have to constantly refactor your cache keys as classes, methods, and parameters change. It's not intended to replace a cache provider. I think what you're looking for would be to just use a NoSql database as your cache provider instead of a MemoryCache or a Dictionary. You can accomplish that by implementing the ICache interface
